---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.3.43.26
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 8954